### ISSUE TITLE
Scala 3 support

### ISSUE THREAD

**Issue by Fristi** [fs2-blobstore/fs2-blobstore#331]
I started with this, but at the moment we have a dependency at shapeless for the url module.

What would you propose to get things working?

**Comment by jgogstad** [comment]
Shapeless is going out, we don't plan to have any direct dependencies on it. It's currently being used for comparing two product types (ip addresses), it was part of an experiment and it's going out before the next release.

The roadmap for the next release is replacing the existing `Path` data model with separate types for urls and paths. It's still experimental and we're going to do some changes to it (capturing hostname validation in the Url type turned out to incur far too much complexity for instance).

I think Scala 3 support is a natural next step. If you want to start working on it, feel free to throw out shapeless from the url module and replace that single use site with just field-by-field comparison.

**Comment by Fristi** [comment]
Thanks for your answer! I'll have a look what I can do to make it work :) And also great it's on your wish list 👍🏻
